baseurl = "http://www.marcore.it/"
languageCode = "en-us"
title = "My New Hugo Site"
copyright = "© 2015 Marco Re"
theme= "greyshade"
[author]
  name = "Marco Re"
  email= "mrc.re@tiscali.it"

[params]
  github_user="marcore"
  twitter_user="marcore78"
  linkedin_user="marcore1"
